In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('./data/titanic.csv')

In [9]:
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [10]:
df['number'].unique()

<StringArray>
['5', '3', '6', 'A', '2', '1', '4']
Length: 7, dtype: str

In [11]:
# Extract numerical part
df['number_numerical'] = pd.to_numeric(df['number'], errors='coerce', downcast='integer')

In [12]:
# Extract cateforical part
df['number_categorical'] = np.where(df['number_numerical'].isnull(), df['number'], np.nan)

df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical
0,NaN,A/5 21171,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,NaN,373450,A,0,NaN,A

In [13]:
df['Cabin'].unique()

<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [14]:
df['Ticket'].unique()

<StringArray>
[       'A/5 21171',         'PC 17599', 'STON/O2. 3101282',
           '113803',           '373450',           '330877',
            '17463',           '349909',           '347742',
           '237736',
 ...
           '349212',           '349217',           '349257',
             '7552', 'C.A./SOTON 34068',  'SOTON/OQ 392076',
           '211536',           '112053',           '111369',
           '370376']
Length: 681, dtype: str

In [15]:
df['cabin_num'] = df['Cabin'].str.extract('(\d+)')  # captures numerical part
df['canib_cat'] = df['Cabin'].str[0]  #capture the first letter

df.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\win\AppData\Local\Temp\ipykernel_10300\3404652738.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['cabin_num'] = df['Cabin'].str.extract('(\d+)')  # captures numerical part

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,canib_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [16]:
df['canib_cat'].value_counts()

canib_cat
C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: count, dtype: int64

In [17]:
# extract the last bit of ticket as number
df['ticket_num'] = df['Ticket'].apply(lambda s: s.split()[-1])
df['ticket_num'] = pd.to_numeric(df['ticket_num'],
                                   errors='coerce',
                                   downcast='integer')

# extract the first part of ticket as category
df['ticket_cat'] = df['Ticket'].apply(lambda s: s.split()[0])
df['ticket_cat'] = np.where(df['ticket_cat'].str.isdigit(), np.nan,
                              df['ticket_cat'])

df.head(20)

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,canib_cat,ticket_num,ticket_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,A/5
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,PC
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,STON/O2.
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN
5,NaN,330877,2,0,2.0,NaN,NaN,NaN,330877.0,NaN
6,E46,17463,2,0,2.0,NaN,46,E,17463.0,NaN
7,NaN,349909,5,0,5.0,NaN,NaN,NaN,349909.0,NaN
8,NaN,347742,1,1,1.0,NaN,NaN,NaN,347742.0,NaN
9,NaN,237736,A,1,NaN,A,NaN,NaN,237736.0,NaN
10,G6,PP 9549,1,1,1.0,NaN,6,G,9549.0,PP
11,C103,113783,1,1,1.0,NaN,103,C,113783.0,NaN
12,NaN,A/5. 2151,3,0,3.0,NaN,NaN,NaN,2151.0,A/5.
13,NaN,347082,3,0,3.0,NaN,NaN,NaN,347082.0,NaN
14,NaN,350406,5,0,5.0,NaN,NaN,NaN,350406.0,NaN
15,NaN,248706,3,1,3.0,NaN,NaN,NaN,248706.0,NaN
16,NaN,382652,3,0,3.0,NaN,NaN,NaN,382652.0,NaN
17,NaN,244373,2,1,2.0,NaN,NaN,NaN,244373.0,NaN
18,NaN,345763,5,0,5.0,NaN,NaN,NaN,345763.0,NaN
19,NaN,2649,4,1,4.0,NaN,NaN,NaN,2649.0,NaN